---
# Copyright 2016, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Create TEMP run dir
  file:
    path: "/var/run/{{ program_name }}"
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_group }}"
    mode: "02755"

- name: Create TEMP lock dir
  file:
    path: "/var/lock/{{ program_name }}"
    state: directory
    owner: "{{ system_user }}"
    group: "{{ system_group }}"
    mode: "02755"

# TODO(mgariepy):
# Remove this in Pike as it only needed to handle upgrades
# from Newton->Newton and Newton->Ocata
- name: Cleanup old tmpfiles.d entry
  file:
    path: "/etc/tmpfiles.d/{{ program_name }}.conf"
    state: absent

- name: Create tmpfiles.d entry
  template:
    src: "ironic-systemd-tmpfiles.j2"
    dest: "/etc/tmpfiles.d/openstack-{{ program_name }}.conf"
    mode: "0644"
    owner: "root"
    group: "root"

- name: Place the systemd init script
  template:
    src: "ironic-systemd-init.j2"
    dest: "/etc/systemd/system/{{ program_name }}.service"
    mode: "0644"
    owner: "root"
    group: "root"
  register: systemd_init

- name: Reload the systemd daemon
  command: "systemctl daemon-reload"
  when: systemd_init | changed
  notify:
    - Restart ironic services
